---
title: Example Graph
---
flowchart TD
    Interface-->|calls|Dispatcher
    Dispatcher-->|calls|Handler
    Handler-->|uses|Service
    Service-->|comprehends|Generator
    Service-->|comprehends|Output
    Service-->|comprehends|Prompt
    Service-->|comprehends|Model
    Generator-->|uses|Prompt
    Generator-->|uses|Model
